/home/cminus-hu/anaconda3/envs/ofa/lib/python3.10/site-packages/torch/distributed/launch.py:181: FutureWarning: The module torch.distributed.launch is deprecated
and will be removed in future. Use torchrun.
Note that --use-env is set by default in torchrun.
If your script expects `--local-rank` argument to be set, please
change it to read from `os.environ['LOCAL_RANK']` instead. See 
https://pytorch.org/docs/stable/distributed.html#launch-utility for 
further instructions

  warnings.warn(
Traceback (most recent call last):
  File "/data/cminus-hu/ofa/run_scripts/vqa/../../train.py", line 477, in <module>
    open(os.path.join(script_path, f'../datasets/OFA_data/sgg/{split}/{template_prefix}_{name}_sample_st_ed_{img_cnt}.json')))
FileNotFoundError: [Errno 2] No such file or directory: '/data/cminus-hu/ofa/run_scripts/vqa/../../../datasets/OFA_data/sgg/50_way/mask_val_sample_st_ed_500.json'
ERROR:torch.distributed.elastic.multiprocessing.api:failed (exitcode: 1) local_rank: 0 (pid: 44370) of binary: /home/cminus-hu/anaconda3/envs/ofa/bin/python
Traceback (most recent call last):
  File "/home/cminus-hu/anaconda3/envs/ofa/lib/python3.10/runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/home/cminus-hu/anaconda3/envs/ofa/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/home/cminus-hu/anaconda3/envs/ofa/lib/python3.10/site-packages/torch/distributed/launch.py", line 196, in <module>
    main()
  File "/home/cminus-hu/anaconda3/envs/ofa/lib/python3.10/site-packages/torch/distributed/launch.py", line 192, in main
    launch(args)
  File "/home/cminus-hu/anaconda3/envs/ofa/lib/python3.10/site-packages/torch/distributed/launch.py", line 177, in launch
    run(args)
  File "/home/cminus-hu/anaconda3/envs/ofa/lib/python3.10/site-packages/torch/distributed/run.py", line 785, in run
    elastic_launch(
  File "/home/cminus-hu/anaconda3/envs/ofa/lib/python3.10/site-packages/torch/distributed/launcher/api.py", line 134, in __call__
    return launch_agent(self._config, self._entrypoint, list(args))
  File "/home/cminus-hu/anaconda3/envs/ofa/lib/python3.10/site-packages/torch/distributed/launcher/api.py", line 250, in launch_agent
    raise ChildFailedError(
torch.distributed.elastic.multiprocessing.errors.ChildFailedError: 
============================================================
../../train.py FAILED
------------------------------------------------------------
Failures:
  <NO_OTHER_FAILURES>
------------------------------------------------------------
Root Cause (first observed failure):
[0]:
  time      : 2023-09-04_13:33:43
  host      : stresstest.local.lan
  rank      : 0 (local_rank: 0)
  exitcode  : 1 (pid: 44370)
  error_file: <N/A>
  traceback : To enable traceback see: https://pytorch.org/docs/stable/elastic/errors.html
============================================================
/home/cminus-hu/anaconda3/envs/ofa/lib/python3.10/site-packages/torch/distributed/launch.py:181: FutureWarning: The module torch.distributed.launch is deprecated
and will be removed in future. Use torchrun.
Note that --use-env is set by default in torchrun.
If your script expects `--local-rank` argument to be set, please
change it to read from `os.environ['LOCAL_RANK']` instead. See 
https://pytorch.org/docs/stable/distributed.html#launch-utility for 
further instructions

  warnings.warn(
Traceback (most recent call last):
  File "/data/cminus-hu/ofa/run_scripts/vqa/../../train.py", line 477, in <module>
    open(os.path.join(script_path, f'../datasets/OFA_data/sgg/{split}/{template_prefix}_{name}_sample_st_ed_{img_cnt}.json')))
FileNotFoundError: [Errno 2] No such file or directory: '/data/cminus-hu/ofa/run_scripts/vqa/../../../datasets/OFA_data/sgg/50_way/mask_val_sample_st_ed_500.json'
ERROR:torch.distributed.elastic.multiprocessing.api:failed (exitcode: 1) local_rank: 0 (pid: 44775) of binary: /home/cminus-hu/anaconda3/envs/ofa/bin/python
Traceback (most recent call last):
  File "/home/cminus-hu/anaconda3/envs/ofa/lib/python3.10/runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/home/cminus-hu/anaconda3/envs/ofa/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/home/cminus-hu/anaconda3/envs/ofa/lib/python3.10/site-packages/torch/distributed/launch.py", line 196, in <module>
    main()
  File "/home/cminus-hu/anaconda3/envs/ofa/lib/python3.10/site-packages/torch/distributed/launch.py", line 192, in main
    launch(args)
  File "/home/cminus-hu/anaconda3/envs/ofa/lib/python3.10/site-packages/torch/distributed/launch.py", line 177, in launch
    run(args)
  File "/home/cminus-hu/anaconda3/envs/ofa/lib/python3.10/site-packages/torch/distributed/run.py", line 785, in run
    elastic_launch(
  File "/home/cminus-hu/anaconda3/envs/ofa/lib/python3.10/site-packages/torch/distributed/launcher/api.py", line 134, in __call__
    return launch_agent(self._config, self._entrypoint, list(args))
  File "/home/cminus-hu/anaconda3/envs/ofa/lib/python3.10/site-packages/torch/distributed/launcher/api.py", line 250, in launch_agent
    raise ChildFailedError(
torch.distributed.elastic.multiprocessing.errors.ChildFailedError: 
============================================================
../../train.py FAILED
------------------------------------------------------------
Failures:
  <NO_OTHER_FAILURES>
------------------------------------------------------------
Root Cause (first observed failure):
[0]:
  time      : 2023-09-04_13:33:58
  host      : stresstest.local.lan
  rank      : 0 (local_rank: 0)
  exitcode  : 1 (pid: 44775)
  error_file: <N/A>
  traceback : To enable traceback see: https://pytorch.org/docs/stable/elastic/errors.html
============================================================
/home/cminus-hu/anaconda3/envs/ofa/lib/python3.10/site-packages/torch/distributed/launch.py:181: FutureWarning: The module torch.distributed.launch is deprecated
and will be removed in future. Use torchrun.
Note that --use-env is set by default in torchrun.
If your script expects `--local-rank` argument to be set, please
change it to read from `os.environ['LOCAL_RANK']` instead. See 
https://pytorch.org/docs/stable/distributed.html#launch-utility for 
further instructions

  warnings.warn(
Traceback (most recent call last):
  File "/data/cminus-hu/ofa/run_scripts/vqa/../../train.py", line 477, in <module>
    open(os.path.join(script_path, f'../datasets/OFA_data/sgg/{split}/{template_prefix}_{name}_sample_st_ed_{img_cnt}.json')))
FileNotFoundError: [Errno 2] No such file or directory: '/data/cminus-hu/ofa/run_scripts/vqa/../../../datasets/OFA_data/sgg/50_way/mask_val_sample_st_ed_500.json'
ERROR:torch.distributed.elastic.multiprocessing.api:failed (exitcode: 1) local_rank: 0 (pid: 45153) of binary: /home/cminus-hu/anaconda3/envs/ofa/bin/python
Traceback (most recent call last):
  File "/home/cminus-hu/anaconda3/envs/ofa/lib/python3.10/runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/home/cminus-hu/anaconda3/envs/ofa/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/home/cminus-hu/anaconda3/envs/ofa/lib/python3.10/site-packages/torch/distributed/launch.py", line 196, in <module>
    main()
  File "/home/cminus-hu/anaconda3/envs/ofa/lib/python3.10/site-packages/torch/distributed/launch.py", line 192, in main
    launch(args)
  File "/home/cminus-hu/anaconda3/envs/ofa/lib/python3.10/site-packages/torch/distributed/launch.py", line 177, in launch
    run(args)
  File "/home/cminus-hu/anaconda3/envs/ofa/lib/python3.10/site-packages/torch/distributed/run.py", line 785, in run
    elastic_launch(
  File "/home/cminus-hu/anaconda3/envs/ofa/lib/python3.10/site-packages/torch/distributed/launcher/api.py", line 134, in __call__
    return launch_agent(self._config, self._entrypoint, list(args))
  File "/home/cminus-hu/anaconda3/envs/ofa/lib/python3.10/site-packages/torch/distributed/launcher/api.py", line 250, in launch_agent
    raise ChildFailedError(
torch.distributed.elastic.multiprocessing.errors.ChildFailedError: 
============================================================
../../train.py FAILED
------------------------------------------------------------
Failures:
  <NO_OTHER_FAILURES>
------------------------------------------------------------
Root Cause (first observed failure):
[0]:
  time      : 2023-09-04_13:34:09
  host      : stresstest.local.lan
  rank      : 0 (local_rank: 0)
  exitcode  : 1 (pid: 45153)
  error_file: <N/A>
  traceback : To enable traceback see: https://pytorch.org/docs/stable/elastic/errors.html
============================================================
/home/cminus-hu/anaconda3/envs/ofa/lib/python3.10/site-packages/torch/distributed/launch.py:181: FutureWarning: The module torch.distributed.launch is deprecated
and will be removed in future. Use torchrun.
Note that --use-env is set by default in torchrun.
If your script expects `--local-rank` argument to be set, please
change it to read from `os.environ['LOCAL_RANK']` instead. See 
https://pytorch.org/docs/stable/distributed.html#launch-utility for 
further instructions

  warnings.warn(
Traceback (most recent call last):
  File "/data/cminus-hu/ofa/run_scripts/vqa/../../train.py", line 477, in <module>
    open(os.path.join(script_path, f'../datasets/OFA_data/sgg/{split}/{template_prefix}_{name}_sample_st_ed_{img_cnt}.json')))
FileNotFoundError: [Errno 2] No such file or directory: '/data/cminus-hu/ofa/run_scripts/vqa/../../../datasets/OFA_data/sgg/50_way/mask_val_sample_st_ed_500.json'
ERROR:torch.distributed.elastic.multiprocessing.api:failed (exitcode: 1) local_rank: 0 (pid: 45680) of binary: /home/cminus-hu/anaconda3/envs/ofa/bin/python
Traceback (most recent call last):
  File "/home/cminus-hu/anaconda3/envs/ofa/lib/python3.10/runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/home/cminus-hu/anaconda3/envs/ofa/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/home/cminus-hu/anaconda3/envs/ofa/lib/python3.10/site-packages/torch/distributed/launch.py", line 196, in <module>
    main()
  File "/home/cminus-hu/anaconda3/envs/ofa/lib/python3.10/site-packages/torch/distributed/launch.py", line 192, in main
    launch(args)
  File "/home/cminus-hu/anaconda3/envs/ofa/lib/python3.10/site-packages/torch/distributed/launch.py", line 177, in launch
    run(args)
  File "/home/cminus-hu/anaconda3/envs/ofa/lib/python3.10/site-packages/torch/distributed/run.py", line 785, in run
    elastic_launch(
  File "/home/cminus-hu/anaconda3/envs/ofa/lib/python3.10/site-packages/torch/distributed/launcher/api.py", line 134, in __call__
    return launch_agent(self._config, self._entrypoint, list(args))
  File "/home/cminus-hu/anaconda3/envs/ofa/lib/python3.10/site-packages/torch/distributed/launcher/api.py", line 250, in launch_agent
    raise ChildFailedError(
torch.distributed.elastic.multiprocessing.errors.ChildFailedError: 
============================================================
../../train.py FAILED
------------------------------------------------------------
Failures:
  <NO_OTHER_FAILURES>
------------------------------------------------------------
Root Cause (first observed failure):
[0]:
  time      : 2023-09-04_13:36:53
  host      : stresstest.local.lan
  rank      : 0 (local_rank: 0)
  exitcode  : 1 (pid: 45680)
  error_file: <N/A>
  traceback : To enable traceback see: https://pytorch.org/docs/stable/elastic/errors.html
============================================================
